/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.TipoProducto;

/**
 *
 * @author Marjorie Acosta Diaz
 */
public class frmEliminarTipo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmEliminarTipo.class.getName());

    /**
     * Creates new form frmEliminarTipo
     */
    public frmEliminarTipo() {
        initComponents();
        System.out.println("Combo tipo creado: " + jcmbTipo2);
        setIconImage(getToolkit().getImage(getClass().getResource("/Resources/iconoLogo2.png")));

    }
    //getters
  public javax.swing.JComboBox<TipoProducto> getcmbTipo() {
        return jcmbTipo2;
    }
  


    public javax.swing.JButton getBtnEliminar() {
        return btnEliminar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBack = new javax.swing.JPanel();
        btnEliminar = new Custom.RoundButton("Eliminar Usuario");
        IconNewUser = new Custom.ImagenPanel("/Resources/edit.png");
        etiTipo = new javax.swing.JLabel();
        jcmbTipo2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpBack.setBackground(new java.awt.Color(255, 255, 255));
        jpBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar.setBackground(new java.awt.Color(51, 51, 51));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jpBack.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 260, 40));

        javax.swing.GroupLayout IconNewUserLayout = new javax.swing.GroupLayout(IconNewUser);
        IconNewUser.setLayout(IconNewUserLayout);
        IconNewUserLayout.setHorizontalGroup(
            IconNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        IconNewUserLayout.setVerticalGroup(
            IconNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jpBack.add(IconNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 130, 120));

        etiTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiTipo.setForeground(new java.awt.Color(0, 0, 0));
        etiTipo.setText("Tipo");
        jpBack.add(etiTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        jcmbTipo2.setBackground(new java.awt.Color(244, 244, 244));
        jcmbTipo2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcmbTipo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbTipo2ActionPerformed(evt);
            }
        });
        jpBack.add(jcmbTipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 260, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpBack, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBack, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jcmbTipo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbTipo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbTipo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmEliminarTipo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IconNewUser;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel etiTipo;
    private javax.swing.JComboBox<TipoProducto> jcmbTipo;
    private javax.swing.JComboBox<TipoProducto> jcmbTipo1;
    private javax.swing.JComboBox<TipoProducto> jcmbTipo2;
    private javax.swing.JPanel jpBack;
    // End of variables declaration//GEN-END:variables
}
