/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.ProductoDAO;
import Model.Proveedor;
import Model.ProveedorDAO;
import Model.TipoProducto;

/**
 *
 * @author Marjorie Acosta Diaz
 */
public class frmEditarProducto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmEditarProducto.class.getName());

    /**
     * Creates new form frmEditarProducto
     */
public frmEditarProducto() {
        initComponents();
        txtNombre.setEnabled(false);
        txtDescripcion.setEnabled(false);
        txtPrecio.setEnabled(false);
        jcmbTipo.setEnabled(false);
        jcmbProveedor.setEnabled(false);
        txtCantidad.setEnabled(false);
        btnGuardar.setEnabled(false);
        cargarProveedores();
        cargarTipo();
        setIconImage(getToolkit().getImage(getClass().getResource("/Resources/iconoLogo2.png")));
    }
    
    //Getters
public javax.swing.JTextField getTxtNombre() {
        return txtNombre;
    }
    public javax.swing.JTextField getTxtDescripcion() {
        return txtDescripcion;
    }
    public javax.swing.JTextField getTxtPrecio() {
        return txtPrecio;
    }
    public javax.swing.JComboBox<TipoProducto> getcmbTipo() {
        return jcmbTipo;
    }
    
    public javax.swing.JComboBox<Proveedor> getcmbProveedor() {
        return jcmbProveedor;
    }
    
    public javax.swing.JTextField getTxtCantidad() {
        return txtCantidad;
    }

    //llenar combo de proveedor
    private void cargarProveedores() {
        ProveedorDAO dao = new ProveedorDAO();
        java.util.List<Proveedor> proveedores = dao.listarProveedor();
        jcmbProveedor.removeAllItems(); // Limpiamos antes de cargar

        for (Proveedor p : proveedores) {  
            jcmbProveedor.addItem(p);
        }
    }
    
    //llenar combo de tipo de producto
    private void cargarTipo() {
        ProductoDAO dao = new ProductoDAO();
        java.util.List<TipoProducto> tipos = dao.listarProducto();
        jcmbTipo.removeAllItems(); // Limpiamos antes de cargar

        for (TipoProducto t : tipos) {  
            jcmbTipo.addItem(t);
        }
    }
    public javax.swing.JTextField getTxtIdProducto() {
        return txtIdProducto;
    }
    
    public javax.swing.JButton getBtnBuscar() {
        return btnBuscar;
    }
    

   
    public javax.swing.JButton getBtnGuardar() {
        return btnGuardar;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBack = new javax.swing.JPanel();
        btnGuardar = new Custom.RoundButton("Eliminar Usuario");
        etiNombre = new javax.swing.JLabel();
        txtNombre = new Custom.RoundTextField(7);
        etiIdProveedor = new javax.swing.JLabel();
        txtIdProducto = new Custom.RoundTextField(7);
        btnBuscar = new Custom.RoundButton("Buscar");
        IconNewUser = new Custom.ImagenPanel("/Resources/edit.png");
        etiProveedor = new javax.swing.JLabel();
        etiDescripcion = new javax.swing.JLabel();
        txtDescripcion = new Custom.RoundTextField(7);
        txtPrecio = new Custom.RoundTextField(7);
        etiPrecio = new javax.swing.JLabel();
        etiTipo = new javax.swing.JLabel();
        txtCantidad = new Custom.RoundTextField(7);
        etiCantidad = new javax.swing.JLabel();
        jcmbProveedor = new javax.swing.JComboBox<>();
        jcmbTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpBack.setBackground(new java.awt.Color(255, 255, 255));
        jpBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setBackground(new java.awt.Color(51, 51, 51));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar cambios");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jpBack.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 260, 40));

        etiNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiNombre.setForeground(new java.awt.Color(0, 0, 0));
        etiNombre.setText("Nombre");
        jpBack.add(etiNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 20));

        txtNombre.setBackground(new java.awt.Color(244, 244, 244));
        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jpBack.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 260, 40));

        etiIdProveedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiIdProveedor.setForeground(new java.awt.Color(0, 0, 0));
        etiIdProveedor.setText("ID del producto");
        jpBack.add(etiIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        txtIdProducto.setBackground(new java.awt.Color(244, 244, 244));
        txtIdProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProductoActionPerformed(evt);
            }
        });
        jpBack.add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 170, 40));

        btnBuscar.setBackground(new java.awt.Color(238, 217, 75));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpBack.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 80, 40));

        javax.swing.GroupLayout IconNewUserLayout = new javax.swing.GroupLayout(IconNewUser);
        IconNewUser.setLayout(IconNewUserLayout);
        IconNewUserLayout.setHorizontalGroup(
            IconNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        IconNewUserLayout.setVerticalGroup(
            IconNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jpBack.add(IconNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 120));

        etiProveedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiProveedor.setForeground(new java.awt.Color(0, 0, 0));
        etiProveedor.setText("Proveedor");
        jpBack.add(etiProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));

        etiDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        etiDescripcion.setText("Descripcion");
        jpBack.add(etiDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        txtDescripcion.setBackground(new java.awt.Color(244, 244, 244));
        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        jpBack.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 260, 40));

        txtPrecio.setBackground(new java.awt.Color(244, 244, 244));
        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        jpBack.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 260, 40));

        etiPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiPrecio.setForeground(new java.awt.Color(0, 0, 0));
        etiPrecio.setText("Precio");
        jpBack.add(etiPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        etiTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiTipo.setForeground(new java.awt.Color(0, 0, 0));
        etiTipo.setText("Tipo");
        jpBack.add(etiTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        txtCantidad.setBackground(new java.awt.Color(244, 244, 244));
        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        jpBack.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 260, 40));

        etiCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiCantidad.setForeground(new java.awt.Color(0, 0, 0));
        etiCantidad.setText("Cantidad");
        jpBack.add(etiCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jcmbProveedor.setBackground(new java.awt.Color(244, 244, 244));
        jcmbProveedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcmbProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbProveedorActionPerformed(evt);
            }
        });
        jpBack.add(jcmbProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 260, 40));

        jcmbTipo.setBackground(new java.awt.Color(244, 244, 244));
        jcmbTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbTipoActionPerformed(evt);
            }
        });
        jpBack.add(jcmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 260, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBack, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBack, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtIdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProductoActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void jcmbProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbProveedorActionPerformed

    private void jcmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbTipoActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmEditarProducto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IconNewUser;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel etiCantidad;
    private javax.swing.JLabel etiDescripcion;
    private javax.swing.JLabel etiIdProveedor;
    private javax.swing.JLabel etiNombre;
    private javax.swing.JLabel etiPrecio;
    private javax.swing.JLabel etiProveedor;
    private javax.swing.JLabel etiTipo;
    private javax.swing.JComboBox<Proveedor> jcmbProveedor;
    private javax.swing.JComboBox<TipoProducto> jcmbTipo;
    private javax.swing.JPanel jpBack;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
