/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Clientes;
import Model.Producto;
import javax.swing.JTable;

/**
 *
 * @author Flia Santos
 */


public class frmNuevaVenta extends javax.swing.JFrame {

    /**
     * Creates new form frmNuevaVenta
     */
    public frmNuevaVenta() {
        initComponents();
        setIconImage(getToolkit().getImage(getClass().getResource("/Resources/iconoLogo2.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCedula1 = new Custom.RoundTextField(7);
        jPanel1 = new javax.swing.JPanel();
        btnRegistrar = new Custom.RoundButton("Registrar nuevo usuario");
        etiCliente = new javax.swing.JLabel();
        etiNombre = new javax.swing.JLabel();
        etiCedula = new javax.swing.JLabel();
        etiTelefono = new javax.swing.JLabel();
        cmbProducto = new javax.swing.JComboBox<>();
        txtTelefono = new Custom.RoundTextField(7);
        txtCedula = new Custom.RoundTextField(7);
        etiTrabajador = new javax.swing.JLabel();
        txtCantidad = new Custom.RoundTextField(7);
        etiProducto = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        etiCantidad = new javax.swing.JLabel();
        txtTrabajador = new Custom.RoundTextField(7);
        btnAgregar = new Custom.RoundButton("Registrar nuevo usuario");
        etiInformacion = new javax.swing.JLabel();
        txtPrecio = new Custom.RoundTextField(7);
        etiPrecio = new javax.swing.JLabel();
        etiDatos = new javax.swing.JLabel();
        etiTotal = new javax.swing.JLabel();
        txtTotal = new Custom.RoundTextField(7);
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtEfectivo = new Custom.RoundTextField(7);
        etiEfectivo = new javax.swing.JLabel();
        etiCambio = new javax.swing.JLabel();
        txtCambio = new Custom.RoundTextField(7);
        btnVerificar = new Custom.RoundButton("Registrar nuevo usuario");

        txtCedula1.setBackground(new java.awt.Color(244, 244, 244));
        txtCedula1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCedula1.setPreferredSize(new java.awt.Dimension(72, 26));
        txtCedula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedula1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(380, 420));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrar.setBackground(new java.awt.Color(238, 217, 75));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistrar.setText("Registrar nueva venta");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 624, 260, 40));

        etiCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiCliente.setText("Información del cliente");
        jPanel1.add(etiCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 120, -1, -1));

        etiNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiNombre.setText("Nombre");
        jPanel1.add(etiNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 158, -1, -1));

        etiCedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiCedula.setText("Cedula");
        jPanel1.add(etiCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 158, -1, -1));

        etiTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiTelefono.setText("Telefono");
        jPanel1.add(etiTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 158, -1, -1));

        cmbProducto.setBackground(new java.awt.Color(244, 244, 244));
        cmbProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductoActionPerformed(evt);
            }
        });
        jPanel1.add(cmbProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 314, 178, 26));

        txtTelefono.setEditable(false);
        txtTelefono.setBackground(new java.awt.Color(244, 244, 244));
        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTelefono.setPreferredSize(new java.awt.Dimension(72, 26));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 190, 164, -1));

        txtCedula.setEditable(false);
        txtCedula.setBackground(new java.awt.Color(244, 244, 244));
        txtCedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCedula.setPreferredSize(new java.awt.Dimension(72, 26));
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 192, 172, -1));

        etiTrabajador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiTrabajador.setText("Nombre");
        jPanel1.add(etiTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 44, -1, -1));

        txtCantidad.setBackground(new java.awt.Color(244, 244, 244));
        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCantidad.setPreferredSize(new java.awt.Dimension(72, 26));
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 314, 164, -1));

        etiProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiProducto.setText("Producto");
        jPanel1.add(etiProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 276, -1, -1));

        cmbCliente.setBackground(new java.awt.Color(244, 244, 244));
        cmbCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClienteActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 190, 176, -1));

        etiCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiCantidad.setText("Cantidad");
        jPanel1.add(etiCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 276, -1, -1));

        txtTrabajador.setBackground(new java.awt.Color(244, 244, 244));
        txtTrabajador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTrabajador.setPreferredSize(new java.awt.Dimension(72, 26));
        txtTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrabajadorActionPerformed(evt);
            }
        });
        jPanel1.add(txtTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 76, 164, -1));

        btnAgregar.setBackground(new java.awt.Color(238, 217, 75));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregar.setText("Agregar Producto");
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 358, 178, 26));

        etiInformacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiInformacion.setText("Información del trabajador");
        jPanel1.add(etiInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        txtPrecio.setEditable(false);
        txtPrecio.setBackground(new java.awt.Color(244, 244, 244));
        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPrecio.setPreferredSize(new java.awt.Dimension(72, 26));
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 314, 170, -1));

        etiPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiPrecio.setText("Precio Unitario");
        jPanel1.add(etiPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 276, -1, -1));

        etiDatos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiDatos.setText("Datos de venta");
        jPanel1.add(etiDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 238, -1, -1));

        etiTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiTotal.setText("Total a pagar");
        jPanel1.add(etiTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 360, -1, -1));

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(244, 244, 244));
        txtTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTotal.setPreferredSize(new java.awt.Dimension(72, 26));
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 390, 164, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Producto", "Precio Unitario", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 499, 530, 113));

        txtEfectivo.setEditable(false);
        txtEfectivo.setBackground(new java.awt.Color(244, 244, 244));
        txtEfectivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEfectivo.setPreferredSize(new java.awt.Dimension(72, 26));
        txtEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEfectivoActionPerformed(evt);
            }
        });
        jPanel1.add(txtEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 76, 164, -1));

        etiEfectivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiEfectivo.setText("Efectivo");
        jPanel1.add(etiEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 44, -1, -1));

        etiCambio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiCambio.setText("Cambio");
        jPanel1.add(etiCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 428, -1, -1));

        txtCambio.setEditable(false);
        txtCambio.setBackground(new java.awt.Color(244, 244, 244));
        txtCambio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCambio.setPreferredSize(new java.awt.Dimension(72, 26));
        txtCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCambioActionPerformed(evt);
            }
        });
        jPanel1.add(txtCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 454, 164, -1));

        btnVerificar.setBackground(new java.awt.Color(0, 204, 51));
        btnVerificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVerificar.setText("Verificar Venta");
        btnVerificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 455, 178, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedula1ActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrabajadorActionPerformed

    private void cmbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbClienteActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void cmbProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProductoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void txtEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEfectivoActionPerformed

    private void txtCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCambioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCambioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNuevaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNuevaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNuevaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNuevaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNuevaVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JComboBox<Clientes> cmbCliente;
    private javax.swing.JComboBox<Producto> cmbProducto;
    private javax.swing.JLabel etiCambio;
    private javax.swing.JLabel etiCantidad;
    private javax.swing.JLabel etiCedula;
    private javax.swing.JLabel etiCliente;
    private javax.swing.JLabel etiDatos;
    private javax.swing.JLabel etiEfectivo;
    private javax.swing.JLabel etiInformacion;
    private javax.swing.JLabel etiNombre;
    private javax.swing.JLabel etiPrecio;
    private javax.swing.JLabel etiProducto;
    private javax.swing.JLabel etiTelefono;
    private javax.swing.JLabel etiTotal;
    private javax.swing.JLabel etiTrabajador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCedula1;
    private javax.swing.JTextField txtEfectivo;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTrabajador;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JComboBox<Clientes> getCmbCliente() { return cmbCliente; }
    public javax.swing.JComboBox<Producto> getCmbProducto() { return cmbProducto; }
    public javax.swing.JButton getBtnRegistrar() { return btnRegistrar; }
    public javax.swing.JButton getBtnAgregar() { return btnAgregar; }
    public javax.swing.JButton getBtnVerificar() { return btnVerificar; }

    public javax.swing.JTextField getTxtCedula() { return txtCedula; }
    public javax.swing.JTextField getTxtTelefono() { return txtTelefono; }
    public javax.swing.JTextField getTxtCantidad() { return txtCantidad; }
    public javax.swing.JTextField getTxtPrecio() { return txtPrecio; }
    public javax.swing.JTextField getTxtTrabajador() { return txtTrabajador; }
    public javax.swing.JTextField getTxtTotal() { return txtTotal; }
    public javax.swing.JTextField getTxtEfectivo() { return txtEfectivo; }
    public javax.swing.JTextField getTxtCambio() { return txtCambio; }

    public JTable getjTable1() { return jTable1; }
    
}
